app/urls.py
from django.conf.urls import patterns, url

__author__ = 'pierre'


urlpatterns = patterns('app.views',
                       url(r'^$', 'direction_map', name='map'),
                       url(r'^submit$', 'direction_map_submit', name='direction-map-submit'),
                       )

padam_test/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = [

    url(r'^map/', include('app.urls')),
    url(r'^$', 'padam_test.views.home', name='home'),

    url(r'^admin/', include(admin.site.urls)),
]

app/models.py
from django.db import models


class MapDirection(models.Model):
    address = models.CharField("Address", max_length=255, blank=False)
    date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.address + ', ' + str(self.date)

app/forms.py
from django.forms import ModelForm

from app.models import MapDirection


class MapDirectionForm(ModelForm):
    class Meta:
        model = MapDirection
        fields = ['address']

app/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.http import Http404, HttpResponse

import logging
import json

from app.forms import MapDirectionForm
from app.models import MapDirection


def direction_map(request):

    form = MapDirectionForm()

    return render(request, 'direction_map.html', {
        'form': form,
    })


def direction_map_submit(request):

    # print("submit_called")
    logging.debug('submit called')

    response_data = {}
    if request.method == 'POST' and request.is_ajax():
        form = MapDirectionForm(request.POST)
        if form.is_valid():
            map_direction = MapDirection()
            map_direction.address = form.cleaned_data.get('address')
            map_direction.save()
            logging.debug("AddressRequested=", map_direction.address)

            response_data['status'] = "success"
        else:
            response_data['status'] = "error"
            response_data['message'] = "Impossible d'obtenir votre itinéraire. Merci de vérifier l'adresse saisie."
        return HttpResponse(json.dumps(response_data), content_type="application/json")
    else:
        raise Http404   # Raise HTTP because that method must be accessed through POST + Ajax

padam_test/views.py
from django.shortcuts import redirect


def home(request):

    return redirect('map')

app/templates/direction_map.html
{% extends 'base.html' %}
{% load static %}

{% block extra_head %}
    <link rel="stylesheet" href="{% static 'css/direction_map.css' %}"/>
{% endblock %}

{% block content %}

    <div class="container">
        <section id="map_section">

            <div class="row">
                <div class="col-md-4"></div>
                <div class="col-md-4">
                    <form id="map-direction-id" action="{% url 'map' %}" method="post">
                        {% csrf_token %}

                        <div class="form-group">
                            <label for="id_address">Email address</label>
                            <input type="text" class="form-control" id="id_address" name="address" maxlength="255">
                        </div>
                        <p id="error"></p>

                        <input type="submit" class="btn btn-default" value="Valider" />
                    </form>
                </div>
                <div class="col-md-4"></div>
            </div>

            <hr class="light">

            <div class="row">

                <div class="map_container">
                    <div id="map"></div>
                </div>
            </div>

        </section>
    </div>

{% endblock %}

{% block extra_scripts %}

    <script src="https://maps.googleapis.com/maps/api/js"></script>

    <script src="{% static 'js/direction_map.js' %}"></script>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
    <head>

        {% include 'head.html' %}

        {% block extra_head %}
        {% endblock %}
    </head>

    <body>

        <header>
            {% include 'nav.html' %}
            {% block extra_header %}
            {% endblock %}
        </header>

        {% block content %}
        {% endblock %}


        {% include 'scripts.html' %}
        {% block extra_scripts %}
        {% endblock %}

    </body>
</html>

templates/head.html
{# Head template #}

{% load static %}

{# Meta #}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="description" content="Python technical test">
<meta name="author" content="Pierre Rodier">
{# Meta END #}

<title>{% block title %}Python technical test{% endblock %}</title>

{# Style #}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
{# Style END #}

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

templates/nav.html
{% load static %}

<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Padam</a>
        </div>
    </div>
</nav>

templates/scripts.html
{# Scripts template #}

{% load static %}

{# Base JS #}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{# Base JS END #}